/**
 * Danh sách quốc tịch.
 * @enum {String}
 */
const nationalities = [
    "Afghan", "Albanian", "Algerian", "American",
    "Andorran", "Angolan", "Antiguan or Barbudan",
    "Argentine", "Armenian", "Australian", "Austrian",
    "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi",
    "Barbadian", "Belarusian", "Belgian", "Belizean",
    "Beninese", "Bhutanese", "Bolivian",
    "Bosnian or Herzegovinian", "Botswanan", "Brazilian",
    "British", "Bruneian", "Bulgarian", "Burkinabé",
    "Burundian", "Cabo Verdean", "Cambodian",
    "Cameroonian", "Canadian", "Central African",
    "Chadian", "Chilean", "Chinese", "Colombian",
    "Comoran", "Congolese (Congo-Brazzaville)",
    "Congolese (Congo-Kinshasa)", "Costa Rican",
    "Croatian", "Cuban", "Cypriot", "Czech",
    "Danish", "Djiboutian", "Dominican",
    "Dominican (Republic)", "Ecuadorian", "Egyptian",
    "Salvadoran", "Equatorial Guinean", "Eritrean",
    "Estonian", "Eswatini", "Ethiopian", "Fijian",
    "Finnish", "French", "Gabonese", "Gambian",
    "Georgian", "German", "Ghanaian", "Greek",
    "Grenadian", "Guatemalan", "Guinean",
    "Bissau-Guinean", "Guyanese", "Haitian",
    "Honduran", "Hungarian",
    "Icelandic", "Indian", "Indonesian", "Iranian",
    "Iraqi", "Irish", "Israeli", "Italian", "Ivorian",
    "Jamaican", "Japanese", "Jordanian",
    "Kazakh", "Kenyan", "Kiribati", "Kuwaiti", "Kyrgyz",
    "Lao", "Latvian", "Lebanese", "Lesotho", "Liberian",
    "Libyan", "Liechtenstein", "Lithuanian", "Luxembourg",
    "Macedonian", "Malagasy", "Malawian", "Malaysian",
    "Maldivian", "Malian", "Maltese", "Marshallese",
    "Mauritanian", "Mauritian", "Mexican",
    "Micronesian", "Moldovan", "Monégasque", "Mongolian",
    "Montenegrin", "Moroccan", "Mozambican", "Myanmar",
    "Namibian", "Nauruan", "Nepalese", "Dutch",
    "New Zealander", "Nicaraguan", "Nigerien",
    "Nigerian", "North Korean", "Norwegian",
    "Omani",
    "Pakistani", "Palauan", "Palestinian", "Panamanian",
    "Papua New Guinean", "Paraguayan", "Peruvian",
    "Philippine", "Polish", "Portuguese",
    "Qatari",
    "Romanian", "Russian", "Rwandan",
    "Saint Kitts and Nevis", "Saint Lucian",
    "Saint Vincentian", "Samoan", "San Marinese",
    "Sao Tomean", "Saudi Arabian", "Senegalese",
    "Serbian", "Seychellois", "Sierra Leonean",
    "Singaporean", "Slovak", "Slovenian",
    "Solomon Islander", "Somali", "South African",
    "South Korean", "South Sudanese", "Spanish",
    "Sri Lankan", "Sudanese", "Surinamese",
    "Swedish", "Swiss", "Syrian",
    "Taiwanese", "Tajik", "Tanzanian", "Thai",
    "Timorese", "Togolese", "Tongan",
    "Trinidadian or Tobagonian", "Tunisian",
    "Turkish", "Turkmen", "Tuvaluan",
    "Ugandan", "Ukrainian", "Emirati", "Uruguayan",
    "Uzbek",
    "Vanuatuan", "Venezuelan", "Vietnamese",
    "Yemeni",
    "Zambian", "Zimbabwean"
];


module.exports = nationalities;
